### PR TITLE
73 refactoring community app

### PR DESCRIPTION
**Pull request by vitorAlves7**
## Description

community app refactoring, added function file and constants

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

image

### CODE REVIEW

**Comment by filipetoyoshima** [comment]
So... what about this pipeline breaking?

Is it being investigated, do you guys need some help?

**Review by filipetoyoshima — CHANGES_REQUESTED** [review]
So... what about this pipeline breaking?

Is it being investigated, do you guys need some help?

**Comment by FranciscoHeronildo** [comment]
Pipeline is apparently OK

**Comment by cjjcastro** [comment]
it was a connection error

**Review by filipetoyoshima — APPROVED** [review]
Ok, it seems to be alright.

**Pull request merged**
