### PR TITLE
100-Feature Get Auth from Plugin

### PR DESCRIPTION
**Pull request by Hiroshi18**
## Description

- The authentication was added for every project and app
- The token is being received via URL in the format
/hubcare_indicators/owner/repo/token/

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by filipetoyoshima — CHANGES_REQUESTED** [review]
`http://localhost:8000/hubcare_indicators/filipetoyoshima/test/<token>` is returning 404

image

**Comment by Hiroshi18** [comment]
> http://localhost:8000/hubcare_indicators/filipetoyoshima/test/<token>

Will test this url

**Comment by Hiroshi18** [comment]
> > http://localhost:8000/hubcare_indicators/filipetoyoshima/test/
> 
> Will test this url
I tried and it worked on the first time
DeepinScreenshot_select-area_20190618212239

**Comment by Hiroshi18** [comment]
Maybe try to rebuild and delete all the sql files

**Review by filipetoyoshima — APPROVED** [review]

**Pull request merged**
