### PR TITLE
16 feature measure pull request quality

### PR DESCRIPTION
**Pull request by Hiroshi18**
## Description
We added the feature to measure the quality of a pull request

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Hiroshi18** [comment]
> The API is breaking when testing on a repository that has no PRs
> 
> image

Thanks will fix

**Comment by Hiroshi18** [comment]
> > The API is breaking when testing on a repository that has no PRs
> > image
> 
> Thanks will fix

I believe this is an DB error not logic

**Comment by Hiroshi18** [comment]
Review it now please

**Comment by filipetoyoshima** [comment]
I've done a test on `nodejs/node` and it takes a lot of time... A LOT. Is that right?

**Pull request merged**
