### PR TITLE
49 feature check if the repository is active

### PR DESCRIPTION
**Pull request by Brian2397**
Feature - Check if the repository is active
## Description

Feature - Check if the repository is active
Check if a repository is active

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cjjcastro** [comment]
image

**Comment by Brian2397** [comment]
the active_question is right now, returning a value between one and zero

**Comment by cjjcastro** [comment]
image

**Comment by cjjcastro** [comment]
I fix the problem, please test

**Comment by RomuloSouza** [comment]
I think now it's correct. Please, take another review @filipetoyoshima. Be careful to test in small repositories, since the logic in pull requests is exceeding our available request limit.

**Comment by Hiroshi18** [comment]
After my pr in the devel there was some conflict in files, i wil fix it and send it back to review

**Comment by Hiroshi18** [comment]
It is okay now no errors and there is only url for the indicators

image

**Pull request merged**
