### PR TITLE
23 feature check the existence of readme

### PR DESCRIPTION
**Pull request by VitorMeirelesOliveira**
## Description

Api gets the existence of a readme at a repository.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

[[selfie-0 uploading...]]
image

### CODE REVIEW

**Comment by Hiroshi18** [comment]
Hello the code is breaking when trying to use.

**Comment by Hiroshi18** [comment]
Or you can fix the try

**Comment by Hiroshi18** [comment]
@Hiroshi18 Test

**Comment by Hiroshi18** [comment]
@Hiroshi18 asdfg

**Comment by Hiroshi18** [comment]
Please fix

**Comment by Hiroshi18** [comment]
test

**Comment by Hiroshi18** [comment]
test

**Comment by filipetoyoshima** [comment]
Recent merges have caused some conflicts.

**Pull request merged**
