### PR TITLE
[WIP] Feature - Check existence of README

### PR DESCRIPTION
**Pull request by cjjcastro**
## Description

Created all features to README.
Config urls to readme.
Created model to readme.
Created serializer to readme.
Config get method to readme api.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

image

### CODE REVIEW

**Comment by filipetoyoshima** [comment]
Oh sh*t, all EPS members were in this code session. Since the reviewer should be some EPS who didn't participate in the issue solution, who are supposed to accept this?

**Comment by Hiroshi18** [comment]
Please fix the conflict in the requirements.txt

**Comment by filipetoyoshima** [comment]
The issue checklist has two items:

- [x] Return if the ReadMe exist
- [ ] The ReadMe can't be the Git standard ReadMe to be considered

At this point, just one is satisfied.

**Comment by filipetoyoshima** [comment]
> Please fix the conflict in the requirements.txt

Done!

**Comment by Hiroshi18** [comment]
Hello, please the code must follow the [pep8](https://www.python.org/dev/peps/pep-0008/) acording to the repo guidelines

**Pull request closed without merging**
