### PR TITLE
19 - Feature - Measure "Help Wanted" Issue Rate

### PR DESCRIPTION
**Pull request by ghost**
## Description
We did the search of Help Wanted using GitHub API, searching for the total issues with Help Wanted, with the URL `issues/help_wanted/< repo owner >/< repo name >/`, where "owner" is the owner of the repository, and the "repo" is the name of the repository, and it returns this way: 
```
{
     "rate": "0.03333333333333333"
}
```
Unable to complete all the tests, due to difficulties with the test procedure, we will be working with this soon.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

image

### CODE REVIEW

**Review by cjjcastro — CHANGES_REQUESTED** [review]
Any new implementation should go first to devel and, after being validated, to the master.
please change your pr to devel

**Comment by Jacoapolinario** [comment]
Sorry for the error (miss click), has already been changed to Devel.

**Review by cjjcastro — APPROVED** [review]

**Comment by filipetoyoshima** [comment]
Warning: The PR name isn't matching with the pattern.

PRs related to issues always start with the issue number

**Review by filipetoyoshima — COMMENTED** [review]
I've manually tested on nodejs/node repo

image

As you can see, it return `0.0`

But on the repo, it says there is 47 "help wanted" from 639 open issues

image

-----

image

**Comment by cjjcastro** [comment]
in the request you can use the labels parameter:

https://api.github.com/repos/nodejs/node/issues?labels=help%20wanted&per_page=100

**Comment by Jacoapolinario** [comment]
The entire PR procedure was performed by counseling. Since the creation of the PR, even his name, has been guidance. I apologize for the mistake. In the meantime, I believe that a consensus among all EPSs is needed on which is the right standard.

**Comment by Jacoapolinario** [comment]
The code was checked along with an EPS, and there was success checking on it prowling in django. I ask that my PR be reviewed. believe that your resquisition, so that your search was carried out in the url, was done incorrectly. if it's not uncomfortable I'll review it.

**Comment by cjjcastro** [comment]
Your PR has been declined because you do not analyze all the issues open in the repository, you analyze the first page, and as you analyze only the first page the information is incomplete

**Comment by RomuloSouza** [comment]
Now I think it's ok, waiting for review

**Comment by RomuloSouza** [comment]
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by filipetoyoshima** [comment]
Still returning `"rate": "0.0"`

image

**Comment by RomuloSouza** [comment]
I've just tested and that's my return for the same repository you've tested
image

I also checked in my cientific calculator and the result was the exatly de same. Please, check if your branch is updated

**Comment by RomuloSouza** [comment]
If your problem persists, please clean your database and run it again

**Comment by filipetoyoshima** [comment]
That's right, it was database problems. Sorry for the mistake

**Review by filipetoyoshima — APPROVED** [review]

**Pull request merged**
