### PR TITLE
15 feature measure the frequent contributors of a repository

### PR DESCRIPTION
**Pull request by vitorAlves7**
## Description

The commits data of the last 30 days with the authors and dates of the commits have been taken and the authors email and the amount of commits that each one has been returned

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

image

### CODE REVIEW

**Comment by Hiroshi18** [comment]
It w

> Well, the solution doesn't accomplish issue #15 exactly how it's required, but I, personally, believe that it is a valid solution
> 
> image
> 
> As you can see, it does not return a number, as required by issue #15, but a list with all contributors. The application could simply count the number of elements in this list to obtain the required measurement. Maybe it creates an _overhead_ when processing this data into the user's machine.
> 
> I need an other EPS review to proceed.

Hello It is okay this way, because we have to know the number of commits and who did it.

**Comment by Hiroshi18** [comment]
Please fix the conflicting files first

**Comment by VitorMeirelesOliveira** [comment]
Maybe there is an error at the logical code at 'contributors_views.py' file and the reason for there is number of contributions at a big repo. Try this api with vscode's repo or rasa's repo, for example.

**Comment by VitorMeirelesOliveira** [comment]
I've just check a similar situation and when I get a requisition for big repos the API doesn't seems to give me back all information. It give me back the first 45 small information for the requisition to the repo. Eg. I asked for issues, then got as response the 45 last issues.

**Comment by Hiroshi18** [comment]
I believe it works in a system that resembles pages you should read the API documentation just to be sure.

**Pull request merged**
